version: '3'

tasks:
  default:
    cmds:
      - task --list

  install:
    desc: Install dependencies
    dir: ugram
    cmds:
      - uv sync

  start-db:
    desc: Start the database container
    dir: ugram
    cmds:
      - docker-compose up -d db

  start-backend:
    desc: Start the backend server (and dependencies)
    dir: ugram
    deps: [start-db]
    cmds:
      - uv run uvicorn src.main:app --reload --port 8000

  start:
    desc: Start the application
    deps: [start-backend]

  test:
    desc: Run tests
    dir: ugram
    cmds:
      - uv run python -m pytest

  test-docker:
    desc: Run tests inside Docker container
    dir: ugram
    cmds:
      - docker compose run --rm api uv run pytest

  lint:
    desc: Run ruff linting
    dir: ugram
    cmds:
      - uv run ruff check .

  format:
    desc: Format code with ruff
    dir: ugram
    cmds:
      - uv run ruff format .

  check:
    desc: Run all checks (format-check, lint, test) for CI
    dir: ugram
    cmds:
      - uv run ruff format --check .
      - uv run ruff check .
      - task: test

